---
- name: Perform aptitude safe-upgrade
  apt: upgrade=safe

- name: Install required system packages.
  apt: pkg={{ item }} state=installed update-cache=yes
  sudo: yes
  with_items:
    - build-essential
    - unzip
    - git
    - libsqlite3-dev
    - sqlite3 # for the command line client
    - libspatialite-dev
    - spatialite-bin
    - g++
    - libx11-dev
    - libpng-dev
    - libjpeg-dev
    - libtiff5-dev
    - libgeotiff-dev
    - libnetcdf-dev
    - libproj-dev
    - libgeos-dev
    - libxml2-dev
    - libpq-dev
    - python-dev
    - python-setuptools
    - python-numpy
    - pkg-config
    - libfreetype6-dev
    - gdal-bin
    - python-gdal
    - libgdal-dev
    - python-pip
    - gfortran
    - liblapack-dev
    - python-qt4

- name: Install latest PIP and Scipy
  pip: name={{ item }} extra_args='--upgrade'
  sudo: yes
  with_items:
    - pip
    - scipy

- name: Install packages required for data science
  pip: name={{ item }}
  sudo: yes
  with_items:
    - ipython
    - pillow
    - netCDF
    - scikit-learn
    - pyzmq
    - jinja2
    - tornado
    - ipdb
    - nose
    - coverage
    - matplotlib
    - Django
    - django-forms-bootstrap
    - django-leaflet
    - jupyter

- name: Symbolic link for libgeos
  file: src=/usr/lib/libgeos-3.4.2.so dest=/usr/lib/libgeos.so state=link
  sudo: yes

- name: Install Basemap
  pip: name=basemap extra_args="--allow-external basemap --allow-unverified basemap"
  sudo: yes
  environment:
    GEOS_DIR: "/usr"

- name: Make default backend for matplotlib
  lineinfile: dest=/usr/local/lib/python2.7/dist-packages/matplotlib/mpl-data/matplotlibrc regexp='backend *: *agg' line='backend : qt4agg'
