---
# file: roles/common/tasks/main.yml
- name: Install required system packages.
  apt: pkg={{ item }} state=installed update-cache=yes
  sudo: yes
  with_items:
    - git
    - libx11-dev
    - g++

- name: Download Miniconda
  get_url:
    url: ftp://ftp.nersc.no/pub/Anton/Miniconda-latest-Linux-x86_64.sh
    #url: http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
    dest: '{{ sources_dir }}/miniconda.sh'
  sudo: yes

- name: Set Miniconda Owner
  file: path={{ sources_dir }}/miniconda.sh owner=vagrant group=vagrant mode=755
  sudo: yes

- name: Install Miniconda
  shell: '{{ sources_dir }}/miniconda.sh -b -p {{ conda_dir }}'
  args:
    creates: '{{ conda_dir }}'

- name: Add Miniconda PATH to .bashrc
  lineinfile: dest=/home/vagrant/.bashrc line="export PATH={{ conda_dir }}/bin:$PATH"

- name: Update Miniconda
  shell: 'export PATH={{ conda_dir }}/bin:$PATH; conda update -q --yes conda'
  args:
    creates: '{{ conda_dir }}/conda-meta/history'

- name: Install scientific Python packages
  shell: 'export PATH={{ conda_dir }}/bin:$PATH; conda install -q --yes {{ item }}'
  with_items:
    numpy
    scipy
    matplotlib
    nose
    pillow
    ipython
    ipython-notebook
    postgresql
    curl
    pycurl
    cython

- name: Install GDAL packages from OSGEO
  shell: 'export PATH={{ conda_dir }}/bin:$PATH; conda install -q --yes -c osgeo {{ item }}'
  with_items:
    - gdal=1.11.2=np19py27_10
    - proj4
    - geos
    - xerces-c
    - libnetcdf=4.3.3.1=0
    - hdf5=1.8.14=10

- name: Add GDAL_DATA to .bashrc
  lineinfile: dest=/home/vagrant/.bashrc line="export GDAL_DATA={{ conda_dir }}/share/gdal"

- name: Install Basemap with PIP
  shell: 'pip install basemap --allow-external basemap --allow-unverified basemap'
  environment:
    PATH: "{{ conda_dir }}/bin:{{ ansible_env.PATH }}"
    GEOS_DIR: "{{ conda_dir }}"
  args:
    creates: '{{ conda_dir }}/lib/python2.7/site-packages/basemap-1.0.7.dist-info'

