---
- name: Update apt-get
  sudo: yes
  apt: update_cache=yes cache_valid_time=36000

- name: Install required system packages.
  apt: pkg={{ item }}
  sudo: yes
  with_items:
    - default-jdk
    - default-jre
    - default-jre-headless
    - cifs-utils

- name: Download TOMCAT
  get_url: url="{{ tomcat_url }}/{{ tomcat_file }}.tar.gz" dest="{{ home }}{{ tomcat_file }}.tar.gz" force=no

- name: Uncompress TOMCAT
  unarchive: src="{{ home }}{{ tomcat_file }}.tar.gz" dest="{{ home }}" copy=no creates="{{ home }}/{{ tomcat_file }}"

- name: Create setenv
  template: src=../templates/tomcat_setenv_sh dest="{{ tomcat_home }}/bin/setenv.sh"

- name: Set setenv to executable
  file: path="{{ tomcat_home }}/bin/setenv.sh" mode=775

- name: Download and deploy THREDDS
  get_url: url="{{ thredds_url }}/{{ thredds_file }}" dest="{{ tomcat_home }}/webapps/{{ thredds_file }}" force=no

- name: Create THREDDS config dir
  file: path={{ tomcat_home }}/content/ state=directory

- name: Stop TOMCAT
  shell: "{{ tomcat_home }}/bin/catalina.sh stop"

- name: Wait for TOMCAT to stop
  wait_for: port=8080 delay=10 state=stopped

- name: Start TOMCAT
  shell: "{{ tomcat_home }}/bin/catalina.sh start"
  async: 10000
  poll: 0
