---
- name: Install required system packages.
  apt: pkg={{ item }}
  sudo: yes
  with_items:
    - default-jdk
    - default-jre
    - default-jre-headless

- name: Download TOMCAT
  get_url: url="{{ tomcat_url }}/{{ tomcat_file }}.tar.gz" dest="{{ shared_dir }}/{{ tomcat_file }}.tar.gz" force=no

- name: Download THREDDS
  get_url: url="{{ thredds_url }}/{{ thredds_file }}" dest="{{ shared_dir }}/{{ thredds_file }}" force=no

- name: Uncompress TOMCAT
  unarchive: src="{{ shared_dir }}/{{ tomcat_file }}.tar.gz" dest="/home/vagrant" copy=no

- name: Create setenv
  template: src=../templates/tomcat_setenv_sh dest="{{ tomcat_home }}/bin/setenv.sh"

- name: Deploy THREDDS
  shell: "cp {{ shared_dir }}/{{ thredds_file }} {{ tomcat_home }}/webapps"

- name: Create THREDDS config dir
  file: path={{ tomcat_home }}/content/thredds state=directory

- name: Push THREDDS config
  synchronize: src={{ thredds_config_home }} dest=/home/vagrant

- name: Deploy THREDDS config
  shell: "cp -r /home/vagrant/nersc-thredds/* {{ tomcat_home }}/content/thredds/"

- name: Start TOMCAT
  shell: "{{ tomcat_home }}/bin/startup.sh"
  async: 10000
  poll: 0
