---
- include: setup_centos.yml
  when: setup_centos is defined and setup_centos

- include: setup_ubuntu.yml
  when: setup_ubuntu is defined and setup_ubuntu

- include: setup_local_vm.yml
  when: setup_local_vm

- include: setup_python.yml
