---
- name: Perform aptitude safe-upgrade
  sudo: yes
  apt: update_cache=yes cache_valid_time=36000

- name: Install required system packages.
  apt: pkg={{ item }}
  sudo: yes
  with_items:
    - git
    - libgfortran3
    - libsqlite3-dev
    - sqlite3
    - libspatialite-dev
    - spatialite-bin
    - libudunits2-0
    - libudunits2-dev


- name: Mount network folders
  sudo: yes
  mount:
    name: "{{ mount_name }}/{{ item }}"
    src: "{{ mount_src }}/{{ item }}"
    fstype: cifs
    opts: "uid=15001,gid=15001,username={{ username }},password={{ password }},domain={{ domain }}"
    state: mounted
  with_items: mounted_dirs

- name: Create shared folder
  file: path="{{ shared_dir }}" state=directory

- name: Download Miniconda
  get_url:
    url: http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
    dest: "{{ shared_dir }}/miniconda.sh"

- name: chmod Miniconda
  file: path="{{ shared_dir }}/miniconda.sh" mode=775

- name: Install Miniconda
  shell: '{{ shared_dir }}/miniconda.sh -b -p {{ conda_dir }}'
  args:
    creates: '{{ conda_dir }}'

- name: Create conda_pkgs in shared folder
  file: path="{{ shared_dir }}/conda_pkgs/empty" state=directory

- name: Copy cached packages from conda_pkgs
  shell: 'cp {{ shared_dir }}/conda_pkgs/* {{ conda_dir }}/pkgs/ -r'

- name: Update Miniconda
  shell: 'conda update -q --yes --copy conda'

- name: Install Nansat requirements
  shell: 'conda install -q --yes --copy {{ item }}'
  with_items:
      #geos=3.3.3
    numpy
    scipy
    matplotlib
    nose
    pillow
    basemap
    proj.4
    netcdf4
    django
    scikit-learn
    nose
    coverage
    jupyter

- name: Instal nansat-gdal and all requirements
  shell: 'conda install -q --yes --copy -c nersc nansat-gdal'

- name: Install nansen-cloud requirements
  pip: name={{ item }}
  with_items:
    - cfunits
    - django-forms-bootstrap
    - django-leaflet
    - ipdb

- name: Clone pysqlite
  git: repo=https://github.com/ghaering/pysqlite
       dest="{{ ansible_env.HOME }}/pysqlite/"
       version=da389878e7c0623cf188387b9fce4fc77d0a9b2c
       update=no
  register: git_pysqlite

- name: Install pysqlite
  shell: 'python setup.py install'
  args:
    chdir: "{{ ansible_env.HOME }}/pysqlite/"
  when: git_pysqlite.changed

- name: Copy downloaded packages to conda_pkgs
  shell: 'cp {{ conda_dir }}/pkgs/*.[bt][zx][2t] {{ shared_dir }}/conda_pkgs/'

- name: Add PATH to .bashrc
  lineinfile: dest=/home/vagrant/.bashrc line="export PATH={{ conda_dir }}/bin:$PATH"

- name: Add GDAL_DATA to .bashrc
  lineinfile: dest=/home/vagrant/.bashrc line="export GDAL_DATA={{ conda_dir }}/share/gdal"

- name: Add links to some conda libraries to /usr/lib
  sudo: yes
  file: src="{{ conda_dir }}/lib/{{ item }}" dest="/usr/lib/{{ item }}" state=link
  with_items:
    - libgeos_c.so
    - libgdal.so

- name: Run ldconfig
  sudo: yes
  shell: 'ldconfig'

- name: Update/checkout Nansat
  git: repo=https://github.com/nansencenter/nansat
       dest="{{ dev_sources_dir }}/nansat/"
       version="{{ nansat_version }}"
       update=yes
  register: git_nansat

- name: Install Nansat (always run to keep the pixel functions updated)
  shell: 'python setup.py build_ext --inplace'
  args:
    chdir: '{{ dev_sources_dir }}/nansat'

- name: Create link from Python dist-packages to nansat
  file: path='{{ python_dist_packages }}/nansat'
        src='{{ dev_sources_dir }}/nansat/nansat'
        state=link
        force=yes

