---
#usepython\tasks\ubuntu.yml
- name: Perform aptitude safe-upgrade
  sudo: yes
  apt: update_cache=yes cache_valid_time=36000

- name: Install required system packages.
  apt: pkg={{ item }}
  sudo: yes
  with_items:
    - git
    - libgfortran3
    - libsqlite3-dev
    - sqlite3
    - libspatialite-dev
    - spatialite-bin