---
- name: Update/checkout OpenWind
  git: repo=https://github.com/nansencenter/openwind
       dest="{{ dev_sources_dir }}/openwind"
       version=develop
       update=yes

- name: Create link from Python dist-packages to openwind
  sudo: yes
  file: path='{{ python_dist_packages }}/openwind'
        src='{{ dev_sources_dir }}/openwind/openwind'
        state=link
        force=yes

- name: Update/checkout Nansen-Cloud Django
  git: repo=https://github.com/nansencenter/nansen-cloud
       dest="{{ dev_sources_dir }}/nansen-cloud"
       version="{{ nansencloud_version }}"
       update=yes

- name: Create link from Python dist-packages to nansen-cloud
  sudo: yes
  file: path='{{ python_dist_packages }}/nansencloud'
        src='{{ dev_sources_dir }}/nansen-cloud/nansencloud'
        state=link
        force=yes

- name: Run migrate on Nansen-Cloud project
  django_manage: >
      command=migrate
      app_path='{{ dev_sources_dir }}/nansen-cloud/project'
      settings='project.settings'
      pythonpath='{{ dev_sources_dir }}/nansen-cloud/project'

- name: Add sample images to db
  django_manage: >
      command='add_images {{ sample_data_dir }}/{{ item.mapper }}/'
      app_path='{{ dev_sources_dir }}/nansen-cloud/project'
  with_items:
    - {name: MER_FRS_1PNPDK20120303_093810_000000333112_00180_52349_3561.N1, mapper: meris_l1}
