---
#usepython\tasks\nansat.yml
- name: nansat | Update/checkout Nansat
  git: repo=https://github.com/nansencenter/nansat
       dest="{{ dev_sources_dir }}/nansat/"
       version="{{ nansat_version }}"
       update=yes
  register: git_nansat
  tags:
    - update-nansat

- name: nansat | Install Nansat (always run to keep the pixel functions updated)
  shell: 'python setup.py build_ext --inplace'
  args:
    chdir: '{{ dev_sources_dir }}/nansat'
  tags:
    - update-nansat

- name: nansat | Create link from Python dist-packages to nansat
  file: path='{{ python_dist_packages }}/nansat'
        src='{{ dev_sources_dir }}/nansat/nansat'
        state=link
        force=yes

- name: nansat | Debug1
  debug: msg="{{ dev_sources_dir }}"

- name: nansat | Debug2
  shell: "echo $PATH"

- name: nansat | Debug3
  shell: "which pip"

- name: nansat | Debug3
  shell: "which nosetests"

- name: nansat | Debug3
  shell: "pip freeze"

- name: nansat | Debug3
  shell: "nosetests nansat"
