language: bash
sudo: false

install:
  - apt-get install virtualbox
  - apt-get install software-properties-common
  - apt-add-repository ppa:ansible/ansible
  - apt-get update
  - apt-get install ansible
  - apt-get install vagrant

script:
  - vagrant up develop
