---
#geo-spaas-vagrant\tasks\django_deploy.yml
- name: Django deploy | create new django project
  become_user: '{{ django_app_user }}'
  shell: 'django-admin.py startproject {{ django_application_name }}'
  args:
    chdir: '{{ django_deploy_root_path }}'
    creates: '{{ django_project_path }}'

- name: Django deploy | create media directories
  file: path='{{ item }}'
        state=directory
        owner={{ django_app_user }}
        group={{ django_app_user }}
  with_items:
    - "{{ geospaas_static_root }}"
    - "{{ geospaas_media_root }}"
    - "{{ geospaas_download_root }}"
    - "{{ geospaas_products_root }}"
    - "{{ django_project_path }}/static"

- name: Django deploy | add _root directories to settings.py
  blockinfile:
    dest: '{{ django_project_path }}/{{ django_application_name }}/settings.py'
    insertafter: EOF
    block: |
        MEDIA_URL = '/site_media/media/'
        STATIC_ROOT = "{{ geospaas_static_root }}"
        MEDIA_ROOT =  "{{ geospaas_media_root }}"
        DOWNLOAD_ROOT = "{{ geospaas_download_root }}"
        PRODUCTS_ROOT = "{{ geospaas_products_root }}"
        STATICFILES_DIRS = [
        "{{ django_project_path }}/static",
        ]

- name: Django deploy | replace DB backend
  replace:
    dest: '{{ django_project_path }}/{{ django_application_name }}/settings.py'
    regexp: 'django.db.backends.sqlite3'
    replace: 'django.contrib.gis.db.backends.spatialite'

- name: Django deploy | replace DB filename
  replace:
    dest: '{{ django_project_path }}/{{ django_application_name }}/settings.py'
    regexp: 'db.sqlite3'
    replace: 'geodjango.db'

- name: Django deploy | replace ALLOWED_HOSTS
  lineinfile:
    dest: '{{ django_project_path }}/{{ django_application_name }}/settings.py'
    insertafter: EOF
    line: "ALLOWED_HOSTS = ['*']"

- name: Django deploy | Add include in urls.py
  lineinfile:
    dest: '{{ django_project_path }}/{{ django_application_name }}/urls.py'
    insertafter: BOF
    line: "{{ item }}"
  with_items:
    - "from django.conf.urls import include"
    - "from django.conf import settings"
    - "from django.conf.urls.static import static"
