---
- name: Setup Python | Update/checkout repositories
  git: repo="https://github.com/nansencenter/{{ item.repo }}"
       dest="{{ dev_sources_dir }}/{{ item.repo }}"
       version="{{ item.version }}"
       update=yes
       force="{{ git_force }}"
  with_items:
    - "{{ core_repos_apps + xtra_repos_apps}}"

- name: Setup Python | Create link from Python dist-packages to repositories
  file: path='{{ python_dist_packages }}/{{ item.app }}'
        src='{{ dev_sources_dir }}/{{ item.repo }}/{{ item.app }}'
        state=link
        force=yes
  with_items:
    - "{{ core_repos_apps + xtra_repos_apps}}"

- name: Django deploy | add apps to settings.py
  blockinfile:
    dest: '{{ django_project_path }}/{{ django_application_name }}/settings.py'
    insertafter: "INSTALLED_APPS"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
    block: |
      '{{ item }}',
  with_items:
    - "{{ geospaas_core_apps + geospaas_xtra_apps}}"

- name: Django deploy | add urlpatterns to urls.py
  lineinfile:
    dest: '{{ django_project_path }}/{{ django_application_name }}/urls.py'
    insertafter: urlpatterns
    line: "{{ item }}"
  with_items:
    - "{{ geospaas_core_urls + geospaas_xtra_urls}}"
