---
# file: roles/sample_datasets/tasks/main.yml
- name: Sample datasets | Create test data folder
  file: path="{{ sample_data_dir }}" state=directory

- name: Sample datasets | Create sample data subfolders (named after nansat mappers)
  file: path="{{ sample_data_dir }}/{{ item.mapper }}" state=directory
  with_items:
    - "{{ sample_files }}"

- name: Sample datasets | Download sample datasets
  get_url:
    url: "{{ sample_data_url }}/{{ item.mapper }}/{{ item.name }}"
    dest: "{{ sample_data_dir }}/{{ item.mapper }}/{{ item.name }}"
    force: no
    timeout: 100
  with_items:
    - "{{ sample_files }}"
  ignore_errors: yes

  #- name: Sample datasets | Create folder for temporary storage of unarchived sample datasets
  #  file: path="{{ home_dir }}/unarchived" state=directory
  #
  #- name: Sample datasets | Extract zipped datasets
  #  unarchive: 
  #    remote_src: yes
  #    src: "{{ item }}"
  #    dest: "{{ home_dir }}/unarchived/
  #  with_items:
  #    find:
  #      paths: "{{ sample_data_dir }}"
  #      patterns: "*.zip"
  #      recurse: yes
  #
  # NOW - how to move the extracted data to the correct folder...?

- name: Sample datasets | Download Nansat landmask
  get_url:
    url: "{{ ftp_nansat_landmask }}/{{ nansat_landmask_file }}"
    dest: "{{ shared_dir }}/{{ nansat_landmask_file }}"
    force: no
    timeout: 100
  ignore_errors: yes

- name: Create Nansat landmask data folder
  file: path="{{ shared_dir }}/MOD44W" state=directory

- name: Sample datasets | Extract Nansat landmask
  unarchive:
    copy: no
    src: "{{ shared_dir }}/{{ nansat_landmask_file }}"
    dest: "{{ shared_dir }}/MOD44W/"
    force: no
  ignore_errors: yes

- name: Sample datasets | Add MOD44WPATH to .bashrc
  lineinfile: dest="{{ home_dir }}/.bashrc" line="export MOD44WPATH={{ shared_dir }}/MOD44W"

- name: Datasets | Add MAPPER_TEST_DATA_DIR to .bashrc
  lineinfile: dest="{{ home_dir }}/.bashrc" line="export MAPPER_TEST_DATA_DIR={{ sample_data_dir }}"
