---
- name: Install | Create conda_pkgs in shared folder
  file: path="{{ cache_dir }}/conda_pkgs/empty" state=directory
  when: use_conda_cache

- name: Install | Copy cached packages from conda_pkgs
  shell: 'cp {{ cache_dir }}/conda_pkgs/* {{ conda_dir }}/pkgs/ -r'
  when: use_conda_cache

- name: Install | Install new packages
  shell: 'conda install -q --yes -c conda-forge {{ item }}'
  with_items:
    - "{{ conda_pkgs }}"

- name: Install | Copy downloaded packages to cached conda_pkgs
  shell: 'cp {{ conda_dir }}/pkgs/*.[bt][zx][2t] {{ cache_dir }}/conda_pkgs/'
  when: use_conda_cache
