---
#usepython\tasks\setup_conda.yml

- name: Conda | Debug
  debug: msg="{{ ansible_ssh_user }} {{ home_dir }} {{ install_dir }} {{ cache_dir }} {{ conda_filename }}"

- name: Conda | Change owner of install directory
  become: yes
  ignore_errors: yes
  file: path="{{ install_dir }}" owner="{{ ansible_ssh_user }}"

- name: Conda | Download Miniconda
  get_url:
    url: 'http://repo.continuum.io/miniconda/{{ conda_filename }}'
    dest: "{{ cache_dir }}/{{ conda_filename }}"

- name: Conda | chmod Miniconda
  file: path="{{ cache_dir }}/{{ conda_filename }}" mode=775

- name: Conda | Install Miniconda
  shell: '{{ cache_dir }}/{{ conda_filename }} -b -p {{ conda_dir }}'
  args:
    creates: '{{ conda_dir }}'

- name: Conda | Update Miniconda
  shell: 'conda update -q --yes --copy conda'

- name: Conda | Add PATH to .bashrc
  lineinfile: dest="{{ home_dir }}/.bashrc" line="export PATH={{ conda_dir }}/bin:$PATH"

- name: nansat | Debug1
  debug: msg="{{ dev_sources_dir }}"

- name: nansat | Debug2
  shell: "echo $PATH"

- name: nansat | Debug3
  shell: "which python"

- name: nansat | STOP
  shell: "BALBLA"
