---
#usepython\tasks\setup_ubuntu.yml
- name: Ubuntu | Perform aptitude safe-upgrade
  become: yes
  apt: update_cache=yes cache_valid_time=36000

- name: Ubuntu | Install required system packages for.
  apt: pkg={{ item }}
  become: yes
  with_items:
    - git
    - libgfortran3
    - libsqlite3-dev
    - sqlite3
    - libspatialite-dev
    - spatialite-bin
    - g++
    - libudunits2-0
    - libudunits2-dev
    - libjpeg-dev
    - libx11-dev
    - xterm

- name: Ubuntu | Add Locale
  lineinfile: dest="{{ home_dir }}/.bashrc" line='export LC_ALL="en_US.UTF-8"'
