---
- name: Install OpenCV
  shell: 'conda install -q --yes -c conda-forge {{ item }}'
  with_items:
    opencv
  
- name: Update/checkout sea_ice_drift
  git: repo=https://github.com/nansencenter/sea_ice_drift
       dest="{{ dev_sources_dir }}/sea_ice_drift"
       version=add_mcc_functions
       update=yes

- name: Create link from Python dist-packages to sea_ice_drift
  file: path='{{ python_dist_packages }}/sea_ice_drift'
        src='{{ dev_sources_dir }}/sea_ice_drift/sea_ice_drift'
        state=link
        force=yes

- name: Update/checkout django-sea-ice-drifters
  git: repo=git@github.com:nansencenter/django-sea-ice-drifters.git
       dest="{{ dev_sources_dir }}/django-sea-ice-drifters"
       version=master
       update=yes

- name: Create link from Python dist-packages to sea_ice_drift
  file: path='{{ python_dist_packages }}/django_sea_ice_drifters'
        src='{{ dev_sources_dir }}/django-sea-ice-drifters/django_sea_ice_drifters'
        state=link
        force=yes

- name: Set names of additional Django apps
  set_fact:
    geospaas_xtra_apps: ["django_sea_ice_drifters"]
    geospaas_xtra_urls: ["url(r'^icedrift/', include('django_sea_ice_drifters.urls')),"]
