---
- name: SVP drifters | Create drifter data folder
  file: path="{{ drifter_data_folder }}" state=directory

- name: SVP drifters | Download drifter datasets
  get_url:
    url: "{{ item.url }}/{{ item.file }}"
    dest: "{{ drifter_data_folder }}/{{ item.file }}"
    force: no
    timeout: 100
  with_items:
    - "{{ drifters }}"
  ignore_errors: yes

- name: SVP drifters | GUNzip drifter datasets
  shell: "yes n | gunzip --keep *.gz"
  args:
    chdir: "{{ drifter_data_folder }}"
  ignore_errors: yes
