---
- name: nansatmap | Run conda install
  include_role:
    name: conda
    tasks_from: conda_install
  vars:
    conda_pkgs:
      - scipy
      - matplotlib
      - basemap
      - basemap-data-hires
      - cmocean

- name: nansatmap | Update/checkout Nansatmap
  git: repo=https://github.com/nansencenter/nansatmap
       dest="{{ dev_sources_dir }}/nansatmap/"
       version="{{ nansatmap_version }}"
       update=yes

- name: nansatmap | Create link from Python dist-packages to nansatmap
  file: path='{{ python_dist_packages }}/nansatmap'
        src='{{ dev_sources_dir }}/nansatmap/nansatmap'
        state=link
        force=yes

- name: nansatmap | Nosetests
  shell: "nosetests nansatmap"
  when: test_nansatmap
  ignore_errors: yes


