---
- name: Local VM | Mount network folders
  become: yes
  mount:
    name: "{{ mount_name }}/{{ item }}"
    src: "{{ mount_src }}/{{ item }}"
    fstype: cifs
    opts: "uid={{ uid }},gid={{ gid }},username={{ username }},password={{ password }},domain={{ domain }}"
    state: mounted
  with_items: mounted_dirs
  when: mount_name is defined
  ignore_errors: yes

- name: Local VM | Create shared folder
  file: path="{{ shared_dir }}" state=directory
  when: shared_dir is defined
