---
- name: Globcurrent | Create drifter data folder
  file: path="{{ drifter_data_folder }}" state=directory

- name: Globcurrent | Download drifter datasets
  get_url:
    url: "{{ item.url }}/{{ item.file }}"
    dest: "{{ drifter_data_folder }}/{{ item.file }}"
    force: no
    timeout: 100
  with_items:
    - "{{ drifters }}"
  ignore_errors: yes

## The following fails... Manually unzip instead..
#- name: Globcurrent | Unarchive gzip files
#  unarchive:
#    src: "{{ item }}"
#    dest: "{{ drifter_data_folder }}"
#    remote_src: yes
#  with_items:
#    - find:
#      paths: "{{ drifter_data_folder }}"
#      patterns: "*.gz"
