---
- name: Globcurrent | Create drifter data folder
  file: path="{{ drifter_data_folder }}" state=directory

- name: Globcurrent | Download drifter datasets
  get_url:
    url: "{{ item.url }}/{{ item.file }}"
    dest: "{{ drifter_data_folder }}/{{ item.file }}"
    force: no
    timeout: 100
  with_items:
    - "{{ drifters }}"
  ignore_errors: yes

