---
- name: Clone nansat-lectures repository
  git: repo=https://github.com/nansencenter/nansat-lectures
       dest="{{ dev_sources_dir }}/nansat-lectures"
       version=master
       update=yes

- name: Add Ipython Notebook to crontab
  cron: name="Jupyter Notebook" special_time=reboot job="sleep 60; {{ conda_dir }}/bin/jupyter-notebook --ip=0.0.0.0 --no-browser --notebook-dir={{ dev_sources_dir }}/nansat-lectures/notebooks/"
