---
- name: Update/checkout Nansat
  git: repo=https://github.com/nansencenter/nansat
       dest="{{ dev_sources_dir }}/nansat/"
       version=develop
       update=yes

- name: Install Nansat
  shell: 'python setup.py install'
  sudo: yes
  args:
    chdir: '{{ dev_sources_dir }}/nansat'
    creates: '/usr/local/lib/python2.7/dist-packages/nansat-0.7_dev.0-py2.7-linux-x86_64.egg'

- name: Update/checkout OpenWind
  git: repo=https://github.com/nansencenter/openwind
       dest="{{ dev_sources_dir }}/openwind"
       version=develop
       update=yes

- name: Install OpenWind
  shell: 'python setup.py install'
  sudo: yes
  args:
    chdir: '{{ dev_sources_dir }}/openwind'
    creates: '/usr/local/lib/python2.7/dist-packages/openwind-0.7_dev.0-py2.7.egg'

- name: Create data folder
  file: path="{{ data_dir }}/" state=directory

  #- name: Download Sentinel-1 sample acquisition
  #  get_url:
  #    url: "ftp://ftp.nersc.no/pub/python_test_data/sentinel1a/{{ sentinel_file }}"
  #    dest: "{{ data_dir }}/{{ sentinel_file }}"
  #    force: no

- name: Download MERIS L1 sample acquisition
  get_url:
    url: "ftp://ftp.nersc.no/pub/python_test_data/meris_l1/{{ meris_l1_file }}"
    dest: "{{ data_dir }}/{{ meris_l1_file }}"
    force: no

- name: Add Ipython Notebook to crontab
  cron: name="Jupyter Notebook" special_time=reboot job=". /etc/environment; /usr/local/bin/jupyter notebook --ip=0.0.0.0 --no-browser --notebook-dir=/home/vagrant/notebooks"

- name: Clone nansat-lectures repository
  git: repo=https://github.com/nansencenter/nansat-lectures
       dest="{{ tutorials_dir }}/nansat-lectures"
       version=master
       update=yes

- name: Create link to the ipython notebooks
  file: path="{{ notebook_dir }}"
        src="{{ tutorials_dir }}/nansat-lectures/notebooks"
        state=link
        force=yes

- name: Create link to mynotebooks folder
  file: path="{{ tutorials_dir }}/nansat-lectures/notebooks/mynotebooks"
        src=/home/vagrant/mynotebooks
        state=link
        force=yes

- name: Restart
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
  sudo: true


