---
- name: Update/checkout Nansat
  git: repo=https://github.com/nansencenter/nansat
       dest="{{ shared_dir }}/nansat/"
       version=develop
       update=yes

- name: Install Nansat
  shell: 'python setup.py install'
  sudo: yes
  args:
    chdir: '{{ shared_dir }}/nansat'
    creates: '/usr/local/lib/python2.7/dist-packages/nansat-0.7_dev.0-py2.7-linux-x86_64.egg'

- name: Update/checkout OpenWind
  git: repo=https://github.com/nansencenter/openwind
       dest="{{ shared_dir }}/openwind"
       version=develop
       update=yes

- name: Install OpenWind
  shell: 'python setup.py install'
  sudo: yes
  args:
    chdir: '{{ shared_dir }}/openwind'
    creates: '/usr/local/lib/python2.7/dist-packages/openwind-0.7_dev.0-py2.7.egg'

- name: Clone nansat-lectures repository
  git: repo=https://github.com/nansencenter/nansat-lectures
       dest="{{ shared_dir }}/nansat-lectures"
       version=master
       update=yes

- name: Add Ipython Notebook to crontab
  cron: name="Jupyter Notebook" special_time=reboot job="sleep 60; . /etc/environment; /usr/local/bin/jupyter notebook --ip=0.0.0.0 --no-browser --notebook-dir={{ shared_dir }}/nansat-lectures/notebooks/"
