---
#course/tasks/main.yml
- name: course | Update/checkout Nansat-Lectures
  git: repo=https://github.com/nansencenter/nansat-lectures
       dest="{{ dev_sources_dir }}/nansat-lectures/"
       update=yes

- name: course | Add Ipython Notebook to crontab
  cron: name="Jupyter Notebook" special_time=reboot job="sleep 60; {{ conda_dir }}/bin/jupyter-notebook --ip=0.0.0.0 --no-browser --notebook-dir={{ dev_sources_dir }}/nansat-lectures/notebooks/"

