---
- hosts: course
  remote_user: vagrant
  sudo: yes
  roles:
      - common
      - course

- hosts: base
  remote_user: vagrant
  sudo: yes
  roles:
      - common
      - base

- hosts: develop
  roles:
    - common
    - develop
