---
- hosts: usepython
  roles:
    - usepython
  environment:
    PATH: "{{ conda_dir }}/bin:{{ ansible_env.PATH }}"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"

- hosts: develop
  roles:
    - sample_datasets
    - nansencloud
  environment:
    PATH: "{{ conda_dir }}/bin:{{ ansible_env.PATH }}"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"

- hosts: doppler
  roles:
    - sample_datasets
    - nansencloud
    - doppler
  environment:
    PATH: "{{ conda_dir }}/bin:{{ ansible_env.PATH }}"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"

- hosts: course
  roles:
    - sample_datasets
    - course
  environment:
    PATH: "{{ conda_dir }}/bin:{{ ansible_env.PATH }}"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"

- hosts: testintegration
  roles:
    - sample_datasets
    - nansencloud
    - testintegration
    - course
  environment:
    PATH: "{{ conda_dir }}/bin:{{ ansible_env.PATH }}"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    MAPPER_TEST_DATA_DIR: "{{ sample_data_dir }}"

- hosts: production
  roles:
    - nansencloud

- hosts: webserver
  roles:
    - webserver

- hosts: thredds
  roles:
    - thredds

