---
- hosts: base
  remote_user: vagrant
  sudo: yes
  roles:
      - common
      - base

- hosts: testconda
  roles:
    - sample_datasets
    - testconda

- hosts: course
  remote_user: vagrant
  roles:
    - sample_datasets
    - course

- hosts: production
  roles:
    - common
    - sample_datasets
    - production

- hosts: develop
  roles:
    - common
    - sample_datasets
    - develop

