---
- hosts: develop
  roles:
    - conda
    - nansat
    - sample_datasets
    - nansencloud
  environment:
    PATH: "{{ conda_dir }}/bin:{{ ansible_env.PATH }}"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"

- hosts: course
  roles:
    - conda
    - nansat
    - sample_datasets
    - course
  environment:
    PATH: "{{ conda_dir }}/bin:{{ ansible_env.PATH }}"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"

- hosts: condarecipes
  roles:
    - conda
    - condarecipes
  environment:
    PATH: "{{ conda_dir }}/bin:{{ ansible_env.PATH }}"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"

- hosts: doppler
  roles:
    - conda
    - nansat
    - sample_datasets
    - nansencloud
    - doppler
  environment:
    PATH: "{{ conda_dir }}/bin:{{ ansible_env.PATH }}"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"

- hosts: processing
  roles:
    - conda
    - nansat
    - nansencloud

- hosts: webserver
  roles:
    - conda
    - nansat
    - nansencloud
    - webserver

- hosts: thredds
  roles:
    - thredds

