---
- hosts: base
  roles:
      - base

- hosts: testconda
  environment:
    PATH: "{{ conda_dir }}/bin:{{ ansible_env.PATH }}"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    MAPPER_TEST_DATA_DIR: "{{ test_data_dir }}"

  roles:
    - testconda

- hosts: course
  remote_user: vagrant
  roles:
    - sample_datasets
    - course

- hosts: production
  roles:
    - common
    - sample_datasets
    - production

- hosts: develop
  roles:
    - common
    - sample_datasets
    - develop

