---
- hosts: miniconda
  roles:
    - miniconda
  environment:
    PATH: "{{ conda_dir }}/bin:{{ ansible_env.PATH }}"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"

- hosts: testintegration
  roles:
    - sample_datasets
    - develop
    - testintegration
    - course
  environment:
    PATH: "{{ conda_dir }}/bin:{{ ansible_env.PATH }}"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    MAPPER_TEST_DATA_DIR: "{{ sample_data_dir }}"

- hosts: develop
  roles:
    - sample_datasets
    - develop
  environment:
    PATH: "{{ conda_dir }}/bin:{{ ansible_env.PATH }}"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"

- hosts: course
  roles:
    - sample_datasets
    - course
  environment:
    PATH: "{{ conda_dir }}/bin:{{ ansible_env.PATH }}"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"

- hosts: production
  roles:
    - sample_datasets
    - develop
  environment:
    PATH: "{{ conda_dir }}/bin:{{ ansible_env.PATH }}"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"

- hosts: thredds
  roles:
    - nersc-thredds
