---
- hosts: all
  roles:
    - common
  environment:
    PATH: "{{ conda_dir }}/bin:{{ ansible_env.PATH }}"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"

- hosts: testintegration
  roles:
    - sample_datasets
    - develop
    - testintegration
    - course
  environment:
    PATH: "{{ conda_dir }}/bin:{{ ansible_env.PATH }}"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    MAPPER_TEST_DATA_DIR: "{{ sample_data_dir }}"

- hosts: develop
  roles:
    - sample_datasets
    - develop

- hosts: course
  roles:
    - course

- hosts: production
  roles:
    - sample_datasets
    - production

