---
- hosts: nansat
  roles:
    - localvm
    - conda
    - nansat
  environment:
    PATH: "{{ conda_dir }}/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    LC_ALL: "en_US.UTF-8"

- hosts: course
  roles:
    - localvm
    - conda
    - nansat
    - sample_datasets
    - course
  environment:
    PATH: "{{ conda_dir }}/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    LC_ALL: "en_US.UTF-8"

- hosts: catalog
  roles:
    - localvm
    - conda
    - nansat
    - sample_datasets
    - catalog
  environment:
    PATH: "{{ conda_dir }}/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    LC_ALL: "en_US.UTF-8"

- hosts: doppler
  roles:
    - localvm
    - conda
    - nansat
    - sample_datasets
    - openwind
    - nansencloud
    - doppler
    - liclipse
  environment:
    PATH: "{{ conda_dir }}/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    LC_ALL: "en_US.UTF-8"

- hosts: travis
  roles:
    - conda
    - nansat
  environment:
    PATH: "{{ conda_dir }}/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    GDAL_DATA: "{{ conda_dir }}/share/gdal"
    LC_ALL: "en_US.UTF-8"
