---
# django_deploy
django_app_user: 'vagrant'
django_deploy_root_path: '{{ dev_sources_dir }}'
django_application_name: 'gesopaas_project'
django_project_path: '{{ django_deploy_root_path }}/{{ django_application_name }}'

geospaas_static_root: "{{ dev_sources_dir }}/site_media/static"
geospaas_media_root: "{{ dev_sources_dir }}/site_media/media/"
geospaas_download_root: "{{ dev_sources_dir }}/site_media/download"
geospaas_products_root: "{{ dev_sources_dir }}/site_media/products"

# django_extend
git_force: no

core_repos_apps:
  - {repo: django-geo-spaas, app: geospaas, version: master}

geospaas_core_apps:
  - geospaas.vocabularies
  - geospaas.catalog
  - geospaas.nansat_ingestor
  - geospaas.viewer
  - django_forms_bootstrap
  - leaflet

geospaas_core_urls:
  - "    url(r'^', include('geospaas.urls')),"
  - "    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)[0],"

xtra_repos_apps: []
geospaas_xtra_apps: []
geospaas_xtra_urls: []

# setup_db
use_local_database: yes
make_migrations: yes
run_migrate: yes

# sample_data2db
add_sample_data: yes
private_sample_files: []
