---
use_local_database: yes
make_migrations: yes
run_migrate: yes
git_force_geospaas: no
add_sample_data: yes
private_sample_files: []

# django_deploy: 

geospaas_repo: django-geo-spaas
geospaas_app: geospaas

geospaas_core_apps:
  - geospaas.vocabularies
  - geospaas.catalog
  - geospaas.nansat_ingestor
  - geospaas.viewer
  - django_forms_bootstrap
  - leaflet

geospaas_core_urls:
  - "    url(r'^', include('geospaas.urls')),"
  - "    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)[0],"

geospaas_xtra_apps: []

geospaas_xtra_urls: []

django_app_user: 'vagrant'

django_deploy_root_path: '{{ dev_sources_dir }}/{{ geospaas_repo }}'
django_application_name: 'project'
django_project_path: '{{ django_deploy_root_path }}/{{ django_application_name }}'

geospaas_static_root: "{{ dev_sources_dir }}/site_media/static"
geospaas_media_root: "{{ dev_sources_dir }}/site_media/media/"
geospaas_download_root: "{{ dev_sources_dir }}/site_media/download"
geospaas_products_root: "{{ dev_sources_dir }}/site_media/products"
