---
# THIS DOESN'T WORK..:
#- name: Add the github SSH public key to the vm authorized_keys
#  authorized_key: user=vagrant key="{{ lookup('file', '/Users/mortenh/.ssh/id_rsa_github.pub') }}"
#
#- name: Update/checkout sar-doppler
#  git: repo=git@github.com:nansencenter/sar-doppler.git
#       dest="{{ dev_sources_dir }}/sar-doppler"
#       version=master
#       update=yes
#       accept_hostkey=yes
#       #key_file=/home/vagrant/.ssh/id_rsa_github

- name: Add GTOPO30 vrt to .bashrc
  lineinfile: dest="{{ home_dir }}/.bashrc" line='export GTOPO30={{ gtopo30_path }}'
  when: mount_network_folders is defined and mount_network_folders

- name: Create link from Python dist-packages to sar-doppler
  sudo: yes
  file: path='{{ python_dist_packages }}/sardoppler'
        src='{{ dev_sources_dir }}/sar-doppler/sardoppler'
        state=link
        force=yes

- name: Create link from Python dist-packages to sar-doppler mappers
  sudo: yes
  file: path='{{ python_dist_packages }}/nansat_mappers'
        src='{{ dev_sources_dir }}/sar-doppler/nansat_mappers'
        state=link
        force=yes

- name: Create Nansat gtopo30 data folder
  file: path="{{ shared_dir }}/gtopo30" state=directory

- name: Add doppler files to db
  django_manage: >
      command='ingest_pattern sat/doppler/ASAR/*.doppler.nc'
      app_path='{{ dev_sources_dir }}/nansen-cloud/project'
  when: mount_network_folders is defined and mount_network_folders 

#- name: Add doppler files to db
#  django_manage: >
#      command='ingest {{ mount_name }}/{{ item.name }}'
#      app_path='{{ dev_sources_dir }}/nansen-cloud/project'
#  with_items:
#    - '{{ doppler_files }}'
#  when: mount_network_folders is defined and mount_network_folders 
#
#- name: Add netcdf files to db
#  django_manage: >
#      command='add_images {{ sample_data_dir }}/asar_netcdf_old_doppler/ASA*.nc'
#      app_path='{{ dev_sources_dir }}/nansen-cloud/project'
#
#- name: Add gsar files to db
#  django_manage: >
#      command='add_images {{ sample_data_dir }}/gsar/*.gsar'
#      app_path='{{ dev_sources_dir }}/nansen-cloud/project'

