---
#nansencloud\tasks\main.yml
- include: setup_centos.yml
  when: setup_centos is defined and setup_centos

- include: setup_ubuntu.yml
  when: setup_ubuntu is defined and setup_ubuntu

- include: extra.yml
  when: nansencloud_extra is defined and nansencloud_extra

#- include: leeFilter.yml - not working..

- include: setup_python.yml

- include: openwind.yml
  when: openwind is defined and openwind

- include: setup_db.yml
  when: add_sample_data is defined and add_sample_data 

- include: sample_data2db.yml
  when: add_sample_data is defined and add_sample_data

