---
- name: Openwind | Update/checkout OpenWind
  git: repo=https://github.com/nansencenter/openwind
       dest="{{ dev_sources_dir }}/openwind"
       version=develop
       update=yes

- name: Openwind | Create link from Python dist-packages to openwind
  file: path='{{ python_dist_packages }}/openwind'
        src='{{ dev_sources_dir }}/openwind/openwind'
        state=link
        force=yes

- name: Openwind | Create link from Python dist-packages to openwind_local_archive.py
  file: path='{{ python_dist_packages }}/openwind_local_archive.py'
        src='{{ dev_sources_dir }}/openwind/templates/openwind_local_archive.py'
        state=link
        force=yes
