---
- name: Sample data to database | Add public sample images to db
  django_manage: >
      command='ingest file://localhost{{ sample_data_dir }}/{{ item.mapper }}/{{ item.name }}'
      app_path='{{ dev_sources_dir }}/nansen-cloud/project'
  with_items:
    - '{{ sample_files }}'
  ignore_errors: yes

- name: Sample data to database | Add private sample images to db
  django_manage: >
      command='ingest file://localhost{{ mount_name }}/{{ item.name }}'
      app_path='{{ dev_sources_dir }}/nansen-cloud/project'
  with_items:
    - '{{ private_sample_files }}'
  when: mount_name is defined and use_local_database is defined and use_local_database
  ignore_errors: yes

