---
- name: Setup DB | Run makemigrations on Nansen-Cloud project
  django_manage: >
      command=makemigrations
      app_path='{{ dev_sources_dir }}/nansen-cloud/project'
      settings='project.settings'
      pythonpath='{{ dev_sources_dir }}/nansen-cloud/project'
  tags:
    - update-nansencloud
  when: make_migrations is defined and make_migrations

- name: Setup DB | Run migrate on Nansen-Cloud project
  django_manage: >
      command=migrate
      app_path='{{ dev_sources_dir }}/nansen-cloud/project'
      settings='project.settings'
      pythonpath='{{ dev_sources_dir }}/nansen-cloud/project'
  tags:
    - update-nansencloud
  when: run_migrate is defined and run_migrate

- name: Setup DB | Load fixture for vocabularies
  django_manage: >
      command='loaddata {{ dev_sources_dir }}/nansen-cloud/nansencloud/vocabularies/fixtures/vocabularies.json'
      app_path='{{ dev_sources_dir }}/nansen-cloud/project'
  when: run_migrate is defined and run_migrate
